site_name: RS-Python
# Copyright
copyright: Copyright &copy; 2024, ESA

theme:
  name: material
  custom_dir: docs/_templates
  features:
    - navigation.tabs
    - navigation.tabs.sticky
    - navigation.sections    
    - navigation.top
    - navigation.tracking
    - navigation.indexes   
    - navigation.path   
    - toc.integrate
    - toc.follow
    - search.suggest
    - search.highlight
    - content.tabs.link
    - content.code.annotation
    - content.code.copy
  language: en
  palette:
    - scheme: default
      toggle:
        icon: material/toggle-switch-off-outline 
        name: Switch to dark mode
      primary: teal
      accent: purple 
    - scheme: slate 
      toggle:
        icon: material/toggle-switch
        name: Switch to light mode    
      primary: teal
      accent: lime

plugins:
  - search
  - mkdocstrings:
      handlers:
        python:
          options:
            separate_modules: true
  # TODO: Add the spellchecker also? If yes, a lot of words should be added in the spellchecker_ignore.txt file
  # - spellcheck:      
  #     known_words: spellchecker_ignore.txt    
  #     # ignore words in <code> tags
  #     ignore_code: yes

  #     # minimum length of words to consider
  #     min_length: 2

  #     # maximum number of capital letters in a word
  #     max_capital: 1

  #     # keep unicode characters
  #     allow_unicode: no

  #     # skip files entirely (supports Unix shell-style wildcards)
  #     skip_files:
  #     - credits.md
  #     - coverage.md
  #     - reference/* 

  #     # whether to only check in strict mode
  #     strict_only: yes   
nav:
- Home:
    - index.md
- RS-Server: 
  - rs-server/docs/doc/index.md
  - User Manual: 
    - rs-server/docs/doc/user_manual.md
    - Overal Architecture: rs-server/docs/doc/users/architecture.md
    - Main Functionalities: rs-server/docs/doc/users/functionalities.md
  - Developer Manual:
    - rs-server/docs/doc/developer_manual.md
    - Tutorials: rs-server/docs/doc/dev/environment/installation.md
    - Guides: rs-server/docs/doc/dev/doc-generation/how-to.md
    - Technical Information:
      - Code style: rs-server/docs/doc/dev/code-style.md
      - API Pyhton: rs-server/docs/doc/api/python/html/index.md
      - API Rest: rs-server/docs/doc/api/rest/index.md
    - Python API Library: 
      - generate_src_doc/rs-server/index.md
      - ADGS: generate_src_doc/rs-server/adgs.md
      - CADIP: generate_src_doc/rs-server/cadip.md        
      - Catalog: generate_src_doc/rs-server/catalog.md
      - Common: generate_src_doc/rs-server/common.md
      - Frontend: generate_src_doc/rs-server/frontend.md
    - Additional information:
      - Tree structure: rs-server/docs/doc/dev/background/tree-structure.md
      - Description: rs-server/docs/doc/dev/environment/description.md
      - Workflow: rs-server/docs/doc/dev/background/workflow.md
      - CI: rs-server/docs/doc/dev/background/ci.md
      - Design: rs-server/docs/doc/dev/design/design.md
      - Description: rs-server/docs/doc/dev/doc-generation/description.md
- RS-Client:
  - rs-client-libraries/docs/doc/index.md
  - Python API Library:
    - generate_src_doc/rs-client/index.md
    - RS-Client Classes: generate_src_doc/rs-client/rs_client.md
    - RS-Client Workflows:
      - generate_src_doc/rs-client/rs_workflows.md
      - Example: generate_src_doc/rs-client/example.md
      - Staging: generate_src_doc/rs-client/staging.md
      - S1 L0: generate_src_doc/rs-client/s1_l0.md

    
