
# Copyright 2023-2026 Airbus, CS Group
#
# Licensed under the Apache License, Version 2.0 (the "License");
# you may not use this file except in compliance with the License.
# You may obtain a copy of the License at
#
#     http://www.apache.org/licenses/LICENSE-2.0
#
# Unless required by applicable law or agreed to in writing, software
# distributed under the License is distributed on an "AS IS" BASIS,
# WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
# See the License for the specific language governing permissions and
# limitations under the License.

version: 1
loggers:
  eopf:
    handlers:
      - console
    propagate: 0

formatters:
  console:
    format: "%(asctime)s - %(name)s - %(levelname)s - %(message)s"

  file:
    format: "%(asctime)s : %(levelname)s : %(module)s : %(funcName)s : %(lineno)d : (Process Details : (%(process)d, %(processName)s), Thread Details : (%(thread)d, %(threadName)s))\nLog : %(message)s"


handlers:
  file:
    class: logging.FileHandler
    level: DEBUG
    formatter: file
    filename: s3ol1.log

  console:
    class: logging.StreamHandler
    level: DEBUG
    formatter: console

root:
  level: INFO
  handlers:
    - file
    - console
