# Copyright 2024 CS Group
#
# Licensed under the Apache License, Version 2.0 (the "License");
# you may not use this file except in compliance with the License.
# You may obtain a copy of the License at
#
#     http://www.apache.org/licenses/LICENSE-2.0
#
# Unless required by applicable law or agreed to in writing, software
# distributed under the License is distributed on an "AS IS" BASIS,
# WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
# See the License for the specific language governing permissions and
# limitations under the License.

name: Generate documentation

# TODO: when to generate the doc ?
# For now, only for new git tags (including hierarchical tags like v1.0/beta), or manually
on:
    push:
    workflow_dispatch:

env:
  PYTHON_VERSION: 3.13.11

jobs:
  generate-documentation:
    name: Generate documentation
    runs-on: ubuntu-latest
    permissions:
      packages: read # to pull docker images when running build_aggregated_openapi.sh
      contents: write # to publish the generated documentation
    steps:
      - uses: actions/checkout@v6
      - uses: ./.github/actions/install-python

      - name: Clone RS-Server/RS-Client/RS-Demo/RS-Infra/RS-Helm
        run: |
          set -x
          pwd
          ls -all
          cd docs
          ls -all

          # We want to use the same branch name (if it exists) in the other
          # cloned repositories as the current branch name
          branch_name=${{ github.ref_name }}

          # Clone rspy repositories
          for repo in rs-server rs-client-libraries rs-demo rs-dpr-service rs-infra-core rs-infra-monitoring rs-workflow-env rs-helm ; do
            git clone https://github.com/RS-PYTHON/${repo}.git
            (cd ${repo}; git checkout $branch_name || git checkout develop)
          done
        working-directory: .
        shell: bash

      - name: Install dependencies
        uses: ./.github/actions/poetry-install
        with:
          options: '--verbose'

      - name: Generate Pydoc in projects
        run: |
          ./.github/scripts/generate_mkdocs.sh
        working-directory: .
        shell: bash

      - name: Generate Markdown HTML documentation
        run: |
          set -x
          pwd
          ls -all
          sleep 2
          poetry run mkdocs gh-deploy --force
        working-directory: .
        shell: bash
